### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'movies.map')

### ISSUE THREAD

**Issue by kb-codes** [iamabhi898/myMoviesApp#16]
I tried running your app by npx react-native run-android but it shows me the error. (mentioned in attachment)

![Screenshot 2021-07-26 202440](https://user-images.githubusercontent.com/81810774/127010625-5b97111f-3fa0-4342-a8ba-2d08a67d5c44.png)

**Comment by iamabhi898** [comment]
Did you installed all the dependencies ? Seems like you are getting error from package react-native-async-storage.

**Comment by iamabhi898** [comment]
> 
> 
> I tried running your app by npx react-native run-android but it shows me the error. (mentioned in attachment)
> 
> ![Screenshot 2021-07-26 202440](https://user-images.githubusercontent.com/81810774/127010625-5b97111f-3fa0-4342-a8ba-2d08a67d5c44.png)

Did you installed all the dependencies ? Seems like you are getting error from package react-native-async-storage.

**Comment by iamabhi898** [comment]
Did you installed all the dependencies by 'npm install' ? Seems like you are getting error from package react-native-async-storage.

**Comment by kb-codes** [comment]
Yes i do install using npm install. But issue remain same

**Comment by iamabhi898** [comment]
Oh, I get it. hahah my bad. I should have mentioned in the Readme file that you will API Key for fetching the data from TMDb, that's why 'movies' is undefined. Get an API key from the TMDb then make a '.env' file and write your API key like "API_KEY=your_api_key" in .env file.

**Comment by kb-codes** [comment]
I get error with another warning, have a look at this

![Uploading Screenshot 2021-07-27 090015.png…]()

**Comment by kb-codes** [comment]
I get it. Thanks bro
